#!/bin/bash
echo "=== DEBUG BACKEND cPanel ==="
echo ""
echo "Esegui questi comandi su cPanel SSH:"
echo ""
echo "# 1. Controlla se l'app è in errore"
echo "tail -50 ~/public_html/gm_v4/passenger.log"
echo ""
echo "# 2. Oppure controlla il log degli errori Apache"
echo "tail -50 ~/logs/error_log"
echo ""
echo "# 3. Verifica che app.py sia corretto"
echo "head -30 ~/public_html/gm_v4/backend/app.py"
echo ""
echo "# 4. Testa se Python può importare il modulo AI"
echo "cd ~/public_html/gm_v4/backend"
echo "source ~/virtualenv/public_html/gm_v4/3.9/bin/activate"
echo "python -c 'from modules.routes.ai import ai_bp; print(\"AI module OK\")'"
echo ""
echo "# 5. Se c'è un errore di sintassi in app.py, controlla:"
echo "python -m py_compile backend/app.py"
