#!/bin/bash
echo "=== Possibili percorsi virtualenv cPanel ==="
echo ""
echo "1. Cerca nella home:"
echo "   find ~/ -name activate -type f 2>/dev/null | grep -i python"
echo ""
echo "2. Possibili percorsi standard cPanel:"
echo "   ~/virtualenv/gm_v4/3.9/bin/activate"
echo "   ~/virtualenv/public_html/gm_v4/3.9/bin/activate"
echo "   ~/.virtualenvs/gm_v4/bin/activate"
echo ""
echo "3. Se il virtualenv non esiste, crealo con:"
echo "   python3.9 -m venv ~/virtualenv/gm_v4_env"
echo "   source ~/virtualenv/gm_v4_env/bin/activate"
echo "   pip install -r ~/public_html/gm_v4/backend/requirements.txt"
echo ""
echo "=== Comandi da eseguire su cPanel SSH ==="
echo ""
echo "# 1. Trova il virtualenv:"
echo "find ~/ -name activate -type f 2>/dev/null | grep -i python | head -5"
echo ""
echo "# 2. Oppure controlla Python disponibili:"
echo "ls -la ~/virtualenv/"
echo ""
echo "# 3. Se trovi il virtualenv, attivalo:"
echo "source PATH_TROVATO/bin/activate"
echo ""
echo "# 4. Poi installa requests:"
echo "pip install requests"
